---

- name: Install packages needed for {{ challenge1_app_appname }}
  ansible.builtin.package:
    name: 
      - python3-flask
      - gunicorn
    state: present

- name: Add {{ challenge1_app_appname }} service account group - {{ challenge1_app_service_group }}
  ansible.builtin.group:
    name: "{{ challenge1_app_service_group }}"
    state: present

- name: Add {{ challenge1_app_appname }} service account user - {{ challenge1_app_service_user }}
  ansible.builtin.user:
    name: "{{ challenge1_app_service_user }}"
    group: "{{ challenge1_app_service_group }}"
    password: "!!"
    comment: "{{ challenge1_app_appname }} service account" 
    createhome: true
    shell: /usr/bin/bash
    state: present

- name: Add ansible controller's SSH key to {{ challenge1_app_service_user }} authorized_keys
  ansible.posix.authorized_key:
    user: "{{ challenge1_app_service_user }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

- name: Configure {{ challenge1_app_appname }} app directory
  ansible.builtin.file:
    path: "/opt/{{ challenge1_app_appname }}"
    state: directory
    mode: '0750'
    owner: "{{ challenge1_app_service_user }}"
    group: "{{ challenge1_app_service_group }}"

- name: deploy main {{ challenge1_app_appname }} files
  ansible.builtin.template:
    src: "files/{{ challenge1_app_appname }}.py.j2"
    dest: "/opt/{{ challenge1_app_appname }}/{{ challenge1_app_appname }}.py"
    mode: '0750'
    owner: "{{ challenge1_app_service_user }}"
    group: "{{ challenge1_app_service_group }}"
  notify: "restart_{{ challenge1_app_appname }}_service"

- name: deploy main {{ challenge1_app_appname }} service unit file
  ansible.builtin.template:
    src: "files/{{ challenge1_app_appname }}.service.j2"
    dest: /etc/systemd/system/{{ challenge1_app_appname }}.service
    mode: '0750'
    owner: root
    group: root
  notify: "restart_{{ challenge1_app_appname }}_service"


- name: Ensure {{ challenge1_app_appname }} service is running
  ansible.builtin.service:
    name: "{{ challenge1_app_appname }}"
    state: started
    enabled: true
