---

- name: Install HAProxy Package
  ansible.builtin.package:
    name: haproxy
    state: present


- name: Configure main HAProxy config
  ansible.builtin.template:
    src: "files/haproxy.cfg.j2"
    dest: /etc/haproxy/haproxy.cfg
