---

- name: Install HAProxy Package
  ansible.builtin.package:
    name: "{{ haproxy_package_name }}"
    state: present


- name: Configure main HAProxy config
  ansible.builtin.template:
    src: "files/haproxy.cfg.j2"
    dest: /etc/haproxy/haproxy.cfg
  notify: restart_{{ haproxy_service_name }}_service

- name: Ensure HAProxy service is running and enabled
  ansible.builtin.service:
    name: "{{ haproxy_service_name }}"
    state: started
    enabled: true
