---

- name: Install packages needed for {{ flaskapp_appname }}
  ansible.builtin.package:
    name: 
      - python3-flask
      - gunicorn
    state: present

- name: Add {{ flaskapp_appname }} service account group
  ansible.builtin.group:
    name: "{{ flaskapp_service_group }}"
    state: present

- name: Add {{ flaskapp_appname }} service account user
  ansible.builtin.user:
    name: "{{ flaskapp_service_user }}"
    group: "{{ flaskapp_service_group }}"
    password: "!!"
    comment: "{{ flaskapp_appname }} service account" 
    createhome: true
    shell: /usr/bin/bash
    state: present

- name: Add ansible controller's SSH key to {{ flaskapp_appname }} service user authorized_keys
  ansible.posix.authorized_key:
    user: "{{ flaskapp_service_user }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

- name: Configure {{ flaskapp_appname }} app directory
  ansible.builtin.file:
    path: "/opt/{{ flaskapp_appname }}"
    state: directory
    mode: '0750'
    owner: "{{ flaskapp_service_user }}"
    group: "{{ flaskapp_service_group }}"

- name: deploy main {{ flaskapp_appname }} files
  ansible.builtin.template:
    src: "files/flask_app.py.j2"
    dest: "/opt/{{ flaskapp_appname }}/{{ flaskapp_appname }}.py"
    mode: '0750'
    owner: "{{ flaskapp_service_user }}"
    group: "{{ flaskapp_service_group }}"
  notify: "restart_{{ flaskapp_appname }}_service"

- name: deploy main {{ flaskapp_appname }} service unit file
  ansible.builtin.template:
    src: "files/myapp.service.j2"
    dest: /etc/systemd/system/{{ flaskapp_appname }}.service
    mode: '0750'
    owner: root
    group: root
  notify: "restart_{{ flaskapp_appname }}_service"


- name: Ensure {{ flaskapp_appname }} service is running
  ansible.builtin.service:
    name: "{{ flaskapp_appname }}"
    state: started
    enabled: true
