---
- hosts: myappnameservers
  gather_facts: false

## NOTE: Throttling to '1' because there seems to be a race condition in the proxmox_kvm module
## and it tries to use the same vmid for every VM when called in quick succession.
## Doesn't really matter though because proxmox can only clone 1 VM at a time from a given template.
  tasks:
    - name: Deploy VMs
      include_role:
        name: proxmox_deploy
        apply:
          delegate_to: "{{ proxmox_api_host }}"
          throttle: 1

- hosts: haproxyservers
  gather_facts: false
  tasks:
    - name: Configure HAProxy VMs
      include_role:
        name: haproxy
