---
- hosts: myappnameservers
  gather_facts: false

## NOTE: Throttling to '1' because there seems to be a race condition in the proxmox_kvm module
## and it tries to use the same vmid for every VM when called in quick succession.
## Doesn't really matter though because proxmox can only clone 1 VM at a time from a given template.
  tasks:
    - name: Deploy VMs
      include_role:
        name: proxmox_deploy
        apply:
          delegate_to: "{{ proxmox_api_host }}"
          throttle: 1

# Make sure the ansible user exists and has our ssh key
- hosts: myappnameservers
  gather_facts: false
  remote_user: root
  
  tasks:
    - name: Add ansible group
      ansible.builtin.group:
        name: ansible
        state: present

    - name: Add ansible user
      ansible.builtin.user:
        name: ansible
        group: ansible
        password: "!!"
        comment: Ansible user
        createhome: true
        state: present

    - name: Add current user's SSH key to ansible user authorized_keys
      ansible.posix.authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

    - name: Enable ansible user to use sudo without a password
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^ansible ALL='
        line: 'ansible ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'


- hosts: haproxyservers
  gather_facts: false
  tasks:
    - name: Configure HAProxy VMs
      include_role:
        name: haproxy
